name: Dr. R.J.Sewell
url: http://rjsewell.github.io
description: "Staff Academic Scientist and Coordinator of Academic Programs"

source: .
safe: true
lsi: false
markdown: kramdown
# pygments: false

highlighter: rogue

permalink: '/blog/:year/:title/'
paginate_path: '/blog/page:num/'
paginate: 2

include: ['_pages']
relative_permalinks: false

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']