name: R.J.Sewell
url: http://rjsewell.github.io
description: "Postdoc at ICFO, Barcelona."

source:      .

safe: true
lsi: false
pygments: true

permalink: /:year/:month/:day/:title/
paginate: 2

include: ['_pages']
relative_permalinks: false

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']